name: sarp
channels:
  - conda-forge
# Using Python3.10
dependencies:
  - ipykernel
  - geopandas
  - xarray[complete]
  - rioxarray
  - dask
  - h5py
  - netcdf4
  - earthaccess
  - openpyxl
  - seaborn
  - bokeh
  - cartopy
  - shapely
  - plotly_express